#! Global Paths
GLOBAL_BASE_PATH: '/mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/fMRI2Vec'
GLOBAL_OUTPUT_DIR: './results/runs'

#! Pain dataset paths
PAIN_CSV_PATH: './src/data/paths_dataset_pain.csv'
PAIN_TRAIN_PKL_PATH: './src/data/pickle_dataset/pain_train.pkl'
PAIN_VAL_PKL_PATH: './src/data/pickle_dataset/pain_val.pkl'

#! ADNI dataset paths
ADNI_CSV_PATH: './src/data/paths_dataset_adni.csv'
ADNI_TRAIN_PATH: './src/data/pickle_dataset/adni_train.pkl'
ADNI_VAL_PATH: './src/data/pickle_dataset/adni_val.pkl'
ADNI_4D_TRAIN_PATH: './src/data/pickle_dataset/adni4D_train.pkl'
ADNI_4D_VAL_PATH: './src/data/pickle_dataset/adni4D_val.pkl'

#! GradCAM (mock) dataset paths
GRADCAM_TRAIN_PATH: './src/data/pickle_dataset/gradcam_train.pkl'
GRADCAM_VAL_PATH: './src/data/pickle_dataset/gradcam_val.pkl'

#! Best models
# BEST_MODEL_PATH: './results/best_models/3DViT_ADNI_patch15_batch32.pth' # ViT 3D Age group ADNI 96% patch 15x15 batch 32 classification 2
BEST_MODEL_PATH: './results/best_models/3DViT_ADNI_patch9_batch32.pth' # ViT 3D Age group ADNI 100% patch 9x9 batch 32 classification 2
# BEST_MODEL_PATH: './results/best_models/3DViT_ADNI_patch15_batch64_output1024.pth' # ViT 3D Age group (balanced) ADNI 76% val patch_9 batch_64 classification_1024
# BEST_MODEL_PATH: './results/best_models/4Dencoder.pth' # 4D encoder with 94% constant validation accuracy
# BEST_MODEL_PATH: './results/runs/last_model.pth'  # For testing


#! Training
TRAINING_SEED: 42
TRAINING_DIM: 3                    # Define 3D or 4D training for the fmriEncoder
TRAINING_EPOCHS: 20
TRAINING_BATCH_SIZE: 64            
TRAINING_ACCUMULATION_STEP: 8      # Accumulation step for Gradient Accumulation
TRAINING_NUM_WORKERS: 16           # Number of workers for data loading
TRAINING_LEARNING_RATE: 0.0001
TRAINING_WEIGHT_DECAY: 0.01        # Default on AdamW is 0.01
TRAINING_DROPOUT: 0.1
TRAINING_VIT_INPUT_SIZE: 80
TRAINING_VIT_PATCH_SIZE: 8

#! Dataset
DATASET_NAME: adni               # pain, adni, adni4D, gradcam
DATASET_SPLIT_RATIO: 0.7
DATASET_GENERATE: False             # Re-generate dataset and save to pickle
DATASET_VISUALIZE_SAMPLES: False    # Visualize samples 1-5 of dataset
DATASET_TRANSFORMS: True           # Apply transforms to dataset in getitem

#! GradCAM
GRADCAM_OUTPUT_DIR: './explainability/xAi_gradcam_ViT3D/adni/'
GRADCAM_SAVE_ATTENTION: False       # Save 3D attention maps to nifti and png 
GRADCAM_THRESHOLD: 5                # Threshold for attention map
GRADCAM_THRESHOLD_3D: 0.5           # Threshold for 3D PNG chart, keep points above this value
GRADCAM_SLICE_DIM: 2                # Sagial (0), Coronal (1), Axial (2)
GRADCAM_SLICE_IDX: 45               # Slice index for visualization

#! Dataset GradCAM
GRADCAM_NUM_SAMPLES: 4000           # Number of samples to generate  
GRADCAM_BACKGROUND_NOISE: 0         # Noise added to all other voxels
GRADCAM_CUBE_SIZE: 8                # Size of the target cube
