# Global
output_dir: './results'
training_enabled: 1
wandb_enabled: 0
cuda_device: 2
dataset_path: './src/data/adni_metadata.pkl'
mini_dataset_path: './src/data/adni_metadata_mini.pkl'
csv_path: '/mnt/data/iai/datasets/ADNI_rsFMRI/paths_ADNI_fMRI_MRI.csv'

# Training
seed: 42
learning_rate: 0.0001
epochs: 1
batch_size: 2             # Test with 32
# weight_decay: 0.1
log_interval: 25           ## Log training loss every 25 batches
projection_dim: 1024