# Data paths
output_dir: './results'
pain_csv: './src/data/paths_dataset_pain.csv'
adni_csv: './src/data/paths_dataset_adni.csv'
adni_train_path: './src/data/adni_train.pkl'
adni_val_path: './src/data/adni_val.pkl'

# best_model_path: '/mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/fMRI2Vec/results/2025-03-20_14-01-28/model-e22.pth' # RESNET age group
# best_model_path: '/mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/fMRI2Vec/results/2025-03-20_10-50-08/model-e28.pth' # RESNET gender
# best_model_path: '/mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/fMRI2Vec/results/2025-03-26_08-41-52/model-e47.pth' # RESNET sMRI age group
# best_model_path: '/mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/fMRI2Vec/results/2025-03-31_16-20-41/model-e8.pth'  # ViT age group (new)
# best_model_path: '/mnt/data/iai/Projects/ABCDE/fmris/CLIP_fmris/fMRI2Vec/results/2025-04-01_14-40-34/model-e3.pth'  # ViT gender (new)


seed: 42
epochs: 10
batch_size: 128            # 128 is max for A100 GPU
num_workers: 16           # Number of workers for data loading
learning_rate: 0.0001
weight_decay: 0.01        # Default on AdamW is 0.01
dropout: 0.1