# Data paths
output_dir: './results'
dataset_train_path: './src/data/adni_timepoints_train.pkl'
dataset_val_path: './src/data/adni_timepoints_val.pkl'
csv_path: '/mnt/data/iai/datasets/ADNI_rsFMRI/ADNI_fMRI_sMRI_paths.csv'
best_model_path: './results/2025-02-19_16-18-01/model-e9.pth'

# Training
seed: 42
epochs: 30
batch_size: 128            # 128 is max for A100 GPU
num_workers: 16           # Number of workers for data loading
learning_rate: 0.0001
weight_decay: 0.01        # Default on AdamW is 0.01
dropout: 0.1