# Global
cuda_device: 1
wandb_enabled: 1
training_enabled: 1

# Data paths
output_dir: './results'
dataset_path: './src/data/adni_timepoints.pkl'
mini_dataset_path: './src/data/adni_timepoints_mini.pkl'
csv_path: '/mnt/data/iai/datasets/ADNI_rsFMRI/ADNI_fMRI_sMRI_paths.csv'

# Training
seed: 42                  # Not used ??
epochs: 5
batch_size: 64             
learning_rate: 0.0003
log_interval: 25           # Log training loss every 25 batches