program: main.py  # name of the program to run
method: bayes     # search method

metric:
  goal: minimize
  name: val_loss # metric to optimize

parameters:
  seed:
    value: 42
  num_workers:
    value: 16
  learning_rate:
    min: 0.0001
    max: 0.0003
  batch_size:
    values: [16, 128]
  epochs:
    values: [5]
  optimizer:
    values: ["AdamW"]
  dropout:
    values: [0.1, 0.2, 0.3, 0.5]
  weight_decay:
    values: [0.01, 0.001]